name: Push image to ghcr.io
on:
  push:
    tags: ["v*"]
  workflow_dispatch:
permissions:
  packages: write
  contents: read # This is required for actions/checkout
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Workaround for running out of disk space
        run: |
          sudo rm -rf /var/lib/docker/tmp
          sudo mkdir -p /mnt/tmp
          sudo ln -s /mnt/tmp /var/lib/docker/tmp
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: ghcr.io/${{ github.actor }}/zephyr-ready:${{ github.event_name == 'workflow_dispatch' && 'latest' || github.ref_name }}
      - run: sudo du /mnt
